appium/appium-windows-driver

lib/installer.js
=> bundle latest winappdriver (1.0-rc)

lib/installer.js
change version and md5 hashes for new msi and executable
=> update installer.js to use 1.0-RC2

lib/installer.js
update Appium installer to install the 1.0 release of WinAppDriver
=> install WinAppDriver v1.0

lib/driver.js, test/unit/driver-specs.js
~~do not merge yet~~
https://discuss.appium.io/t/compare-images-with-appium-and-opencv-using-windowsdriver/25469
=> add compare_images in no proxy list

lib/commands/index.js, lib/commands/touch.js, package.json
Attempting to create command wrapper, but not seeming to work - very novice in JS, so pointers welcome!
=> Touch wrapper to allow clicking by image

lib/commands/general.js
Fix for https://github.com/appium/appium-windows-driver/issues/70
Comments welcome as appreciate I've probably committed a range of faux-pas!
=> fix: Use winforms dimensions

lib/commands/record-screen.js, package.json
Same as appium/appium-android-driver#637
=> chore: Update file upload procedure

lib/desired-caps.js, lib/driver.js, package.json
The previous implementation was using non-existing args to createSession call. Not sure how it worked before
=> refactor: Update port allocation logic

lib/desired-caps.js
The capabilities are described in WAD documentation, but were not present in the constraints file
=> chore: Add missing caps

lib/commands/general.js, lib/commands/index.js, lib/commands/powershell.js, lib/driver.js
Just because we can. I'll also have to write some documentation for it later and build other features that need PS
=> feat: Add a possibility to execute Power Shell scripts

lib/driver.js
Fixes https://github.com/appium/appium/issues/14829
=> fix: Do not add `app` routes to NO_PROXY list

lib/installer.js, lib/winappdriver.js, package.json
Actually, this is an async implementation of https://github.com/appium/appium-windows-driver/pull/110
cc @blakee1
=> refactor: Tune the procedure of WAD install path lookup

README.md, lib/installer.js
Hi
I want to set WAD path to my custom local path not `ProgramFiles`, `ProgramFiles(x86)`
So i added WAD custom local path in env.
Thanks for reviewing this PR.
=> feat: Enable setting WAD local path

lib/commands/general.js, lib/driver.js, lib/installer.js
Addresses https://github.com/appium/appium/issues/16316
=> feat: Make it possible to request element rect

lib/driver.js
Addresses https://github.com/appium/appium/issues/16934
=> fix: Add proxyCommand method

README.md
Based on https://github.com/microsoft/WinAppDriver/blob/master/Docs/AuthoringTestScripts.md#supported-locators-to-find-ui-elements
=> docs: add element locator table

.github/workflows/unit-test.yml
https://github.com/appium/appium-windows-driver/actions/runs/3507720244/jobs/5875643209
=> ci: Try to resolve EPERM issue on npm upgrade

README.md, lib/commands/app-management.js, lib/commands/execute.js, lib/commands/index.js, lib/installer.js
=> feat: Add closeApp and launchApp extension commands

.releaserc, package.json
Noticed this repo did not have this changelog yet
https://github.com/appium/appium-safari-driver/pull/44/files
=> chore: add release changelog

.releaserc, package.json
I forgot customizing changelogs to include more commit messages
=> chore: update release rc

README.md, lib/commands/winapi/user32.js, package.json
Related to https://github.com/appium/appium/issues/18291
=> chore: Move napi-based modules to optional dependencies

.github/workflows/functional-test.yml, README.md, lib/commands/gestures.js, lib/commands/winapi/user32.js, package.json, test/e2e/commands/winapi-e2e-specs.js
ffi-napi has been abandoned and is not being maintained anymore.
=> feat: Migrate native code from ffi-napi to koffi

lib/installer.js, lib/registry.js, lib/utils.js
https://github.com/appium/appium/issues/17271
=> feat: Allow to elevate system privileges in runtime

README.md, lib/commands/clipboard.js, lib/commands/execute.js, lib/commands/index.js, lib/utils.js
Finished https://github.com/appium/appium-windows-driver/pull/72
=> feat: Add extensions to get and set Windows clipboard

README.md
=> docs: add newCommandTimeout in README.md

lib/desired-caps.js, lib/driver.js
Constraints and Opts type exporting like XCUItest driver.
What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_
=> chore(types): export constraints and opts types

lib/commands/general.js
Addresses https://github.com/appium/dotnet-client/issues/812#issuecomment-2275085538
=> fix: Add workaround for setting the window position

lib/driver.js, lib/winappdriver.js
https://github.com/appium/appium/pull/21021
=> fix: Accept reqBasePath proxy option

lib/driver.js
Addresses https://github.com/appium/appium-windows-driver/issues/297
=> fix: Update windowsSetClipboard method mapping

scripts/install-wad.mjs
https://github.com/appium/appium-windows-driver/issues/324
=> fix: Use msiexec to install WAD
