appium/appium-windows-driver

- lib/installer.js
Modified the installer.js file to point to the [v0.5 release of WinAppDriver](https://github.com/Microsoft/WinAppDriver/releases/tag/v0.5-beta)
> Updated installer.js file for WinAppDriver v0.5 release

- lib/driver.js
- lib/winappdriver.js
This enables concurrent sessions by giving each WinAppDriver.exe instance a different port.  Port assignment is dynamic, starting at 5000 and when the process dies that port # is free again.
One example of why we need multiple concurrent sessions for Windows Desktop is sometimes a desktop session is needed to interact with system elements (like taskbar), while at the same time there is an active session with the application being tested.
> adding multiple concurrent session support

- lib/logger.js
- package.json
Get rid of the deprecated `appium-logger` package.
> Move to logger from appium-support

- lib/winappdriver.js
This is a Windows specific feature allowing you to not use "app" as a desired capability.  
Was originally submitted back in October and missed getting it in.  Would like to make sure this is included in future releases.
> resubmitting PR #15 - removing app from required parameters

- lib/installer.js
Updated Appium installer to install latest v1.1 RC of WinAppDriver. Please squash the two commits when accepting if possible. Thank you!
> WinAppDriver v1.1RC Install

- lib/installer.js
Updated appium-windows-driver to point to the latest v1.1 version of WinAppDriver.
Thanks!
> Updated lib/installer.js to point to latest (official) WinAppDriver v1.1 release.

- README.md
- lib/desired-caps.js
- lib/driver.js
- lib/winappdriver.js
- package.json
add create session timeout and waitForCondition to retry the session creation in case of an error
add 'createSessionTimeout' capability, WindowsDriver only
> #13173 WinAppDriver does not wait long startup an UWP app

- lib/installer.js
It includes two important features:
1. ms:waitForAppLaunch
2. ms:experimental-webdriver
> use WinAppDriver v1.2 Release Candidate

- lib/commands/find.js
- lib/commands/general.js
- lib/commands/index.js
- lib/driver.js
- lib/winappdriver.js
https://github.com/appium/appium/issues/14073
> feat: Add findByImage support to Windows driver

- lib/commands/find.js
WinAppDirver declares it does support implicit timeouts on its own, so there is no need to repeat this functionality on the driver level: https://github.com/microsoft/WinAppDriver/blob/master/Tests/WebDriverAPI/Timeouts.cs
> fix: Use built-in timeouts

- .azure-pipelines.yml
- lib/installer.js
- lib/winappdriver.js
- package.json
- test/e2e/driver-e2e-specs.js
- test/e2e/installer-e2e-specs.js
https://github.com/appium/appium/issues/13261
Also:
- Switched file download to use Axios lib, which is more effective and to avoid possible memory leaks. 
- Made isAdmin helper result memoizable
- Enabled integration tests, which don't require admin
> refactor: Do not require hashsum match after driver download is completed

- lib/driver.js
- package.json
We had issues with file-based locking in UIA2 driver, so I aligned the implementation of Windows driver to not repeat the same mistakes.
> chore: Update port allocation logic

- lib/desired-caps.js
Add browserName to the desiredCapConstraints for compatibility with selenium-appium, since selenium-webdriver requires that browserName is present, so selenium-appium must provide it in capabilities.
Without the fix, we get the current error when trying to run `react-native-windows` application tests:
```
[BaseDriver] The following capabilities were provided, but are not recognized by Appium:
[BaseDriver]   browserName
```
Refs:
- https://github.com/react-native-windows/selenium-appium/blob/fadfd0a2e45603991e0ae908c1b5acbfe91b1792/src/WinAppDriver.ts#L10
- https://github.com/SeleniumHQ/selenium/blob/d8ddb4d83972df0f565ef65264bcb733e7a94584/javascript/node/selenium-webdriver/index.js#L613-L620
Note: There still seems to be more compatibility issues between `selenium-appium` and the 1.15.0 …
> fix: browserName for selenium-appium compatibility

- lib/desired-caps.js
- lib/driver.js
The problem there is that Appium umbrella driver writes all parameters provided as arguments into desired capabilities, so we are getting an unexpected conflict in this case where WAD port is set equal to the Appium port if the latter is provided via the command line. I've changed the capability name to `systemPort` in order to avoid that. See https://github.com/appium/appium/issues/14829#issuecomment-723135229 for more details
> fix: Change the capability name for the port number

- README.md
- lib/commands/powershell.js
- lib/constants.js
- lib/desired-caps.js
- lib/driver.js
We have a command to run PS scripts, but this could only be executed during a session. And sometimes it is necessary to perform some preparation steps right before the session is actually executed. Then `prerun` capability could be in use
> feat: Add a possibility to execute prerun scripts before session startup

- package.json
fix https://github.com/appium/appium/issues/15056
@mykola-mokhnach not sure what automation name should be: "Windows" or "WinAppDriver"?
> feat: make windows driver appium 2.0 compatible

- lib/commands/execute.js
Now if I execute `driver.execute_script('powerShell', {'command': "Some PS command"})`, the value `powerShell` will be passed to `execPowerShell` method and driver throw `Power Shell script/command must not be empty` exception.
This fix enable to execute PS scripts/commands via `execute` API method.
> Proper call of execPowerShell method from execute

- lib/installer.js
- lib/registry.js
- lib/winappdriver.js
- test/unit/registry-specs.js
https://github.com/microsoft/WinAppDriver/releases/tag/v1.2.99
This build also got an updated install script, which allows to actually uninstall WAD. The script is now is distributed for multiple architectures and has `.exe` extension instead of `.msi`
> feat: Bump WAD installer version to 1.2.99

- lib/winappdriver.js
The default base path in Appium 2 proxy is `/`, while WAD sets the one to `/wd/hub`. I've updated the logic to properly align them
> fix: Properly set base path for the proxy

- lib/driver.js
https://github.com/appium/appium/issues/17577
Actually current appium-windows-driver does not have `tag name`
(https://github.com/microsoft/WinAppDriver/blob/master/Tests/WebDriverAPI/Element.cs has test code to use the tag name locator)
> feat: add "tag name" support in the locator

- README.md
Elements indexing in xpath starts from 1
Also locators like `//node[x]` might be confusing, because they are not going to select the x-th element in the tree, but rather each x-th element in the hierarchy. Usually, what users want could be achieved by adding parentheses: `(//node)[x]`
> docs: Tune xpath locator example

- README.md
- lib/commands/winapi/user32.js
Related to https://github.com/appium/appium-windows-driver/issues/229
> fix: Tune `windows: scroll` API

- lib/commands/gestures.js
- lib/commands/winapi/user32.js
Related to https://github.com/appium/appium/issues/19796
> fix: Perform click action when necessary

- lib/commands/execute.js
Inspired by https://github.com/appium/appium-mac2-driver/pull/327#discussion_r1939668545
> chore: Avoid throwing generic error for an unknown execute script name

- lib/commands/context.ts
- lib/driver.js
- test/e2e/commands/context-e2e-specs.js
- test/unit/driver-specs.js
The task is to support a single NATIVE_APP context for a smooth context switching between the plugin using the Context API and the Windows driver.
> feat: Support context api

- lib/commands/record-screen.js
when recording screen multiple times, only the last recorded file gets deleted, while the previously recorded files all remain in the temporary directory.
> fix: Clearing previous recorded video if start new one.

- lib/commands/record-screen.js
- lib/driver.js
- lib/execute-method-map.ts
Add missing parameter `videoFilter` to executeMethodMap of startRecordingScreen.
Recover default recording screen functions with default type of parameters.
`AppiumDriver.startRecordScreen()` `POST appium/start_recording_screen` `{"options": { ... }}`
`AppiumDriver.stopRecordScreen()` ..
> fix: executeMethodMap of startRecordingScreen

- README.md
- lib/commands/general.js
- lib/desired-caps.ts
- lib/driver.js
- lib/winappdriver.js
Addresses https://github.com/appium/appium-windows-driver/issues/305
> feat: Implement wadUrl capability

- lib/winappdriver.js
Thank you again for accepting my proposal for a change and implementing it so fast. It's just this small bug that's left to fix, so that it works with every possible custom WAD URL. Currently it doesn't work for URLs like this one: http://127.0.0.1:4723. For it, 2 slashes are added like that: http://127.0.0.1:4723//status. The fix fixes this only case where it doesn't work.
> fix: Remove trailing slash from proxyOpts for custom server URL

- lib/commands/log.ts
- lib/driver.js
- test/e2e/commands/log-e2e-specs.js
Codes from android(uiautomator2) and xcuitest drivers.
only support 'server' type.
Server logs are being handled in the same way even if the drivers are different. Wouldn't it be possible to change the way they are processed to a method like the one used by the context API in plugins? For example, by consolidating the logs in the base driver's getLogTypes method with a structure like ['server', ...pluginResults, ...driverResults], server log handling could be done in one place within the base driver's getLogTypes and getLog methods.
> feat: Support log commands

- lib/utils.js
to fix:
```
kazu $ npm run build
> appium-windows-driver@4.4.5 build
> tsc -b
lib/utils.js:24:3 - error TS2322: Type '{ stdout: string | Buffer<ArrayBufferLike>; stderr: string | Buffer<ArrayBufferLike>; }' is not assignable to type '{ stdout: string; stderr: string; }'.
Types of property 'stdout' are incompatible.
Type 'string | Buffer<ArrayBufferLike>' is not assignable to type 'string'.
Type 'Buffer<ArrayBufferLike>' is not assignable to type 'string'.
24   return await B.resolve(execAsync(fullCmd, opts))
~~~~~~
```
> fix: fix type error

- lib/utils.js
Addresses https://github.com/appium/appium-windows-driver/issues/324
> fix: Shellexec args escaping on Windows
